"""Initial schema

Revision ID: 7a2072e1479a
Revises:
Create Date: 2026-08-09 01:38:13.872936

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a2072e1479a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("tax_id", sa.String(length=50), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customers_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_customers_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_customers_phone"), ["phone"], unique=False)

    op.create_table(
        "parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("part_type", sa.String(length=50), nullable=True),
        sa.Column("brand", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("min_stock_level", sa.Integer(), nullable=True),
        sa.Column("sku", sa.String(length=50), nullable=True),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_parts_barcode"), ["barcode"], unique=True)
        batch_op.create_index(batch_op.f("ix_parts_brand"), ["brand"], unique=False)
        batch_op.create_index(batch_op.f("ix_parts_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_parts_part_type"), ["part_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_parts_sku"), ["sku"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_parts_stock_quantity"), ["stock_quantity"], unique=False
        )

    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("contact_no", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("staff", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_staff_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_staff_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_staff_role"), ["role"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_staff_username"), ["username"], unique=True
        )

    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("contact_no", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("contact_person", sa.String(length=100), nullable=True),
        sa.Column("payment_terms", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_suppliers_name"), ["name"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(length=20), nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("old_values", sa.Text(), nullable=True),
        sa.Column("new_values", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action_date"), ["action_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action_type"), ["action_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_record_id"), ["record_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_table_name"), ["table_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "backup_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backup_date", sa.DateTime(), nullable=False),
        sa.Column("backup_type", sa.String(length=20), nullable=True),
        sa.Column("backup_location", sa.String(length=500), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tables_included", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("backup_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backup_logs_backup_date"), ["backup_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backup_logs_backup_type"), ["backup_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backup_logs_status"), ["status"], unique=False
        )

    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_date", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("receipt_number", sa.String(length=100), nullable=True),
        sa.Column("vendor", sa.String(length=100), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=True),
        sa.Column("recurring_frequency", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expenses_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_expenses_expense_date"), ["expense_date"], unique=False
        )

    op.create_table(
        "maintenance_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("equipment_name", sa.String(length=100), nullable=False),
        sa.Column("equipment_serial", sa.String(length=100), nullable=True),
        sa.Column("maintenance_date", sa.DateTime(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("performed_by", sa.String(length=100), nullable=True),
        sa.Column("vendor", sa.String(length=100), nullable=True),
        sa.Column("parts_used", sa.Text(), nullable=True),
        sa.Column("next_maintenance", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(["part_id"], ["parts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("maintenance_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_maintenance_logs_maintenance_date"),
            ["maintenance_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_logs_maintenance_type"),
            ["maintenance_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_logs_next_maintenance"),
            ["next_maintenance"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_logs_part_id"), ["part_id"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("action_text", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["staff.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_is_read"), ["is_read"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_type"), ["type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("order_date", sa.DateTime(), nullable=False),
        sa.Column("expected_date", sa.DateTime(), nullable=True),
        sa.Column("received_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_expected_date"),
            ["expected_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_order_date"), ["order_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_order_number"), ["order_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_supplier_id"), ["supplier_id"], unique=False
        )

    op.create_table(
        "sales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_date", sa.DateTime(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("payment_status", sa.String(length=20), nullable=True),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sales_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sales_payment_method"), ["payment_method"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sales_payment_status"), ["payment_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sales_receipt_number"), ["receipt_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_sales_sale_date"), ["sale_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sales_staff_id"), ["staff_id"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("setting_key", sa.String(length=100), nullable=False),
        sa.Column("setting_value", sa.Text(), nullable=True),
        sa.Column("setting_type", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=True),
        sa.Column("validation_regex", sa.String(length=200), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category", "setting_key", name="uq_settings_category_key"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_settings_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_settings_setting_key"), ["setting_key"], unique=False
        )

    op.create_table(
        "stock_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.DateTime(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("reference_type", sa.String(length=20), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(["part_id"], ["parts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_entries_entry_date"), ["entry_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_entries_movement_type"),
            ["movement_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_entries_part_id"), ["part_id"], unique=False
        )

    op.create_table(
        "supplier_part",
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("supplier_sku", sa.String(length=50), nullable=True),
        sa.Column("cost_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("is_preferred", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["part_id"], ["parts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("supplier_id", "part_id"),
    )
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.DateTime(), nullable=False),
        sa.Column("log_level", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_system_logs_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_system_logs_log_date"), ["log_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_system_logs_log_level"), ["log_level"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_system_logs_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_system_logs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(["sale_id"], ["sales.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payments_sale_id"), ["sale_id"], unique=False
        )

    op.create_table(
        "purchase_order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_order_id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("received_quantity", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tax_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("line_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["part_id"], ["parts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"], ["purchase_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_order_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_order_items_part_id"), ["part_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_order_items_purchase_order_id"),
            ["purchase_order_id"],
            unique=False,
        )

    op.create_table(
        "sale_details",
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tax_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("line_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["part_id"], ["parts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sale_id"], ["sales.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sale_id", "part_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sale_details")
    with op.batch_alter_table("purchase_order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_order_items_purchase_order_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_order_items_part_id"))

    op.drop_table("purchase_order_items")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_sale_id"))

    op.drop_table("payments")
    with op.batch_alter_table("system_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_system_logs_request_id"))
        batch_op.drop_index(batch_op.f("ix_system_logs_log_level"))
        batch_op.drop_index(batch_op.f("ix_system_logs_log_date"))
        batch_op.drop_index(batch_op.f("ix_system_logs_category"))

    op.drop_table("system_logs")
    op.drop_table("supplier_part")
    with op.batch_alter_table("stock_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_entries_part_id"))
        batch_op.drop_index(batch_op.f("ix_stock_entries_movement_type"))
        batch_op.drop_index(batch_op.f("ix_stock_entries_entry_date"))

    op.drop_table("stock_entries")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_setting_key"))
        batch_op.drop_index(batch_op.f("ix_settings_category"))

    op.drop_table("settings")
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sales_staff_id"))
        batch_op.drop_index(batch_op.f("ix_sales_sale_date"))
        batch_op.drop_index(batch_op.f("ix_sales_receipt_number"))
        batch_op.drop_index(batch_op.f("ix_sales_payment_status"))
        batch_op.drop_index(batch_op.f("ix_sales_payment_method"))
        batch_op.drop_index(batch_op.f("ix_sales_customer_id"))

    op.drop_table("sales")
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_orders_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_status"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_order_number"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_order_date"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_expected_date"))

    op.drop_table("purchase_orders")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_read"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_category"))

    op.drop_table("notifications")
    with op.batch_alter_table("maintenance_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_maintenance_logs_part_id"))
        batch_op.drop_index(batch_op.f("ix_maintenance_logs_next_maintenance"))
        batch_op.drop_index(batch_op.f("ix_maintenance_logs_maintenance_type"))
        batch_op.drop_index(batch_op.f("ix_maintenance_logs_maintenance_date"))

    op.drop_table("maintenance_logs")
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_expense_date"))
        batch_op.drop_index(batch_op.f("ix_expenses_category"))

    op.drop_table("expenses")
    with op.batch_alter_table("backup_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backup_logs_status"))
        batch_op.drop_index(batch_op.f("ix_backup_logs_backup_type"))
        batch_op.drop_index(batch_op.f("ix_backup_logs_backup_date"))

    op.drop_table("backup_logs")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_table_name"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_record_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action_date"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suppliers_name"))

    op.drop_table("suppliers")
    with op.batch_alter_table("staff", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_staff_username"))
        batch_op.drop_index(batch_op.f("ix_staff_role"))
        batch_op.drop_index(batch_op.f("ix_staff_name"))
        batch_op.drop_index(batch_op.f("ix_staff_email"))

    op.drop_table("staff")
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parts_stock_quantity"))
        batch_op.drop_index(batch_op.f("ix_parts_sku"))
        batch_op.drop_index(batch_op.f("ix_parts_part_type"))
        batch_op.drop_index(batch_op.f("ix_parts_name"))
        batch_op.drop_index(batch_op.f("ix_parts_brand"))
        batch_op.drop_index(batch_op.f("ix_parts_barcode"))

    op.drop_table("parts")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customers_phone"))
        batch_op.drop_index(batch_op.f("ix_customers_name"))
        batch_op.drop_index(batch_op.f("ix_customers_email"))

    op.drop_table("customers")
    # ### end Alembic commands ###
